# config/prometheus/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'factorit'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']